### ISSUE TITLE
TypeError: write() only accepts bytes, unicode, and dict objects

### ISSUE THREAD

**Issue by rtiwariops** [jupyterhub/kerberosauthenticator#12]
When trying to access jupyterhub using the url I am getting following exception.

 Traceback (most recent call last):
      File "/root/env/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/root/env/lib/python3.6/site-packages/kerberosauthenticator/auth.py", line 43, in get
        self.raise_auth_required()
      File "/root/env/lib/python3.6/site-packages/kerberosauthenticator/auth.py", line 36, in raise_auth_required
        self.write(data)
      File "/root/env/lib/python3.6/site-packages/tornado/web.py", line 841, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects

**Comment by jbreitman** [comment]
Has this issue been addressed?  I have observed the same issue.

**Comment by KarelMacek** [comment]
Hello, same issue here.
    
Traceback (most recent call last):
      File "/usr/local/lib64/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.9/site-packages/kerberosauthenticator/auth.py", line 45, in get
        self.raise_auth_required()
      File "/usr/local/lib/python3.9/site-packages/kerberosauthenticator/auth.py", line 36, in raise_auth_required
        self.write(data)
      File "/usr/local/lib64/python3.9/site-packages/tornado/web.py", line 841, in write
        raise TypeError(message)
    TypeError: <class 'coroutine'>write() only accepts bytes, unicode, and dict objects

**Comment by KarelMacek** [comment]
Not sure if it is relevant. The documentation states that I need to carry out:
` chown jupyterhub:admin /etc/jupyterhub/HTTP.keytab

which returns
` chown: invalid user: ‘jupyterhub:admin’

It is not a big surprise. When following the official installation documentation, no users are created https://jupyterhub.readthedocs.io/en/stable/quickstart.html#installation (pip variant).

**Comment by KarelMacek** [comment]
Another remark - working with Python 3.9 - may that be an issue?

**Comment by jcrist** [comment]
At the time this was written everything worked fine (including the setup instructions). However, it's been over 2 years since I wrote this and JupyterHub (and tornado) have likely made changes since then. I lack any bandwidth to fix this myself, but if someone wants to figure out what changes are needed and push a PR I'd happily merge it.

**Comment by kamon405** [comment]
I ran into this problem. It has to do with JupyterHub. Any version above 1.1.0 and this error comes up. I had version 1.4.2 of JupyterHub installed, and that's when this issue came up. I performed a downgrade back to JupyterHub version 1.1.0 and this resolved the issue. So it's a compatibility issue with the most recent version of JupyterHub.  I don't have the bandwidth to fix this similar to jcrist. Will keep my current version running until this bug is fixed, or I find a viable alternative.

**Comment by fj11** [comment]
When you call render_template function, set sync=True. then you won't have this error.

**Comment by jbreitman** [comment]
Thanks @fj11.  Adding sync=True to the render_template function in kerberosauthenticator/auth.py resolved the issue.

**Comment by oogunsanwo** [comment]
I am having this same issue with Jupyterhub 3.1.1 but not sure how to include sync=True in my code

**Comment by jbreitman** [comment]
I am no longer using this module, but believe this will help.

Find the location of auth.py associated with kerberosauthenticator.
Copy the original file to /var/tmp.
Edit the file and look for the function below.  I believe this is what I did.

data = self.render_template(
            'kerberos_login_error.html',
            login_url=self.settings['login_url'],
            sync=True
        ) 

You will need to restart the service after you edit the file.
Copy the file back into place if this does not work and restart the service.

Reference
https://github.com/jupyterhub/kerberosauthenticator/blob/master/kerberosauthenticator/auth.py

**Comment by manics** [comment]
Should be fixed by https://github.com/jupyterhub/kerberosauthenticator/pull/13 (there'll hopefully be a new release soon)
